package org.vu.pskdemo.mybatis.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.STUDENTGROUP_ID
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    private Long studentgroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.NAME
     *
     * @return the value of PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.NAME
     *
     * @param name the value for PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.SURNAME
     *
     * @return the value of PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.SURNAME
     *
     * @param surname the value for PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.STUDENTGROUP_ID
     *
     * @return the value of PUBLIC.STUDENT.STUDENTGROUP_ID
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    public Long getStudentgroupId() {
        return studentgroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.STUDENTGROUP_ID
     *
     * @param studentgroupId the value for PUBLIC.STUDENT.STUDENTGROUP_ID
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    public void setStudentgroupId(Long studentgroupId) {
        this.studentgroupId = studentgroupId;
    }
}