package org.vu.pskdemo.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import org.vu.pskdemo.mybatis.model.Course;

@Mapper
public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    int insert(Course row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    Course selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    List<Course> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    int updateByPrimaryKey(Course row);
}