package org.vu.pskdemo.mybatis.dao;

import java.util.List;
import org.mybatis.cdi.Mapper;
import org.vu.pskdemo.mybatis.model.Student;

@Mapper
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    int insert(Student row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    Student selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    List<Student> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Mon Mar 04 22:39:08 EET 2024
     */
    int updateByPrimaryKey(Student row);

    List<Student> selectByGroupId(Long groupId);
}